# Generated by Django 2.2.28 on 2023-03-07 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='comments',
            new_name='review_text',
        ),
    ]
