# Generated by Django 2.2.28 on 2023-03-08 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0002_auto_20230307_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='age_rating',
            field=models.CharField(default='NR', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='film',
            name='photo',
            field=models.ImageField(blank=True, upload_to='film_images'),
        ),
        migrations.AddField(
            model_name='review',
            name='dislikes',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
