# Generated by Django 2.1.5 on 2023-03-10 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0005_auto_20230310_1503'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='screen',
        ),
        migrations.RemoveField(
            model_name='screening',
            name='screen_num',
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
        migrations.DeleteModel(
            name='Screen',
        ),
        migrations.DeleteModel(
            name='Screening',
        ),
    ]
