# Generated by Django 2.1.5 on 2023-03-17 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0005_alter_film_slug'),
        ('cinema', '0006_auto_20230310_1637'),
    ]

    operations = [
    ]
