# Generated by Django 2.2.28 on 2023-03-17 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0010_auto_20230317_1149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='likes',
        ),
    ]
